/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Restaurant {
    public boolean someLibraryMethod() {
        return true;
    }

//Create class representing Restaurant(name, number of stars betweeen 0 and 5, price category (i.e. number of dollar signs)).
//Implement Restaurant constructor.
//Test that your Restaurant constructor is behaving reasonably.
//Implement a reasonable toString method for Restaurants.
//Write a test to create an instance of Restaurant and ensure that its toString is working properly.

}
