/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

//Write a method called roll that accepts an integer n and rolls a six-sided dice n times. The method should return an array containing the values of the rolls.


//Write a method called containsDuplicates that returns true or false depending on whether the array contains duplicate values.


//Given an array of arrays calculate the average value for each array and return the array with the lowest average.


